### ISSUE TITLE
不能更改默认的端口号

### ISSUE THREAD

**Issue by qinyunchuan** [papan01/LiveStreamer#4]
程序在JNI中默认了8554端口号，修改Andriod代码中的RTSP端口号无效

**Comment by qinyunchuan** [comment]
JNI在19版本的NDK中无法编译通过，作者能够上传一个RTSP端口号生效版本的jni lib库？

**Comment by qinyunchuan** [comment]
我修改了jni库，需要的可以找我

**Comment by diguasange** [comment]
> 程序在JNI中默认了8554端口号，修改Andriod代码中的RTSP端口号无效

请问你怎么修改的jni库，在源工程中没有发现jni层C/C++代码，仅有libstreamer.so。另外请问，该动态库包含了live555中哪个库（BasicUsageEnvironment、UsageEnvironment、groupsock、liveMedia）,谢谢回复
邮箱：946071400@qq.com

**Comment by papan01** [comment]
@qinyunchuan  感謝您的提醒，已發現在
live_streamer.cpp的constructer未將port傳入rtspPort。
LiveStreamer::LiveStreamer(unsigned int fps, unsigned int port) {
    queueSize = 40;
    fps = 25;
    rtpPortNum = 20000;
    rtcpPortNum = rtpPortNum+1;
    ttl = 5;
    rtspPort = port;**original 8554**
    rtspOverHTTPPort = 0;
    multicast = false;
    useMmap = true;
    url = "papan01";
    murl = "papan01";
    useThread = true;
    maddr = INADDR_NONE;
    repeatConfig = true;
    timeout = 65;
    _authDB = NULL;
    quit = 0;
}

會在找時間更新，謝謝。
